### ISSUE TITLE
Error: Column matching query does not exist

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#1569]
- I get this error from the records endpoint on a specific table.
- The table is the Checkouts table, created using our original method (in Cycle 2) of importing tsv files and running the my SQL transform. (I'm not getting the error from the Checkouts table loaded via Brent's SQL data.)
- I was not getting the error prior to merging #1545. Now, with that code, I get the error consistently.

I can do more work to try providing better reproduction steps if needed. 

<details>

<summary><h3>Traceback</h3></summary>

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/api/db/v0/tables/16/records/

Django Version: 3.1.14
Python Version: 3.9.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 53, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/db/viewsets/records.py", line 65, in list
    records = paginator.paginate_queryset(
  File "/code/mathesar/api/pagination.py", line 89, in paginate_queryset
    records = query.get_records(
  File "/code/mathesar/models/query.py", line 121, in get_records
    return self.db_query.get_records(**kwargs)
  File "/code/mathesar/models/query.py", line 149, in db_query
    initial_columns=self._db_initial_columns,
  File "/code/mathesar/models/query.py", line 157, in _db_initial_columns
    return tuple(
  File "/code/mathesar/models/query.py", line 158, in <genexpr>
    _db_initial_column_from_json(json_col)
  File "/code/mathesar/models/query.py", line 208, in _db_initial_column_from_json
    column_pair = _get_column_pair_from_id(col_json["id"])
  File "/code/mathesar/models/query.py", line 203, in _get_column_pair_from_id
    col = Column.objects.get(id=col_id)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /api/db/v0/tables/16/records/
Exception Value: Column matching query does not exist.
```

</details>

**Comment by pavish** [comment]
@seancolsen @zackkrida I'd like us to close this issue. I assume it has something to do with the reflection mechanism we had earlier, and I think it may no longer be relevant.
