### ISSUE TITLE
Fix exploration transformations

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3868]
## Steps to reproduce

1. Run off the `explorations` branch used for #3855
1. Run a very simple exploration like this

    ![image](https://github.com/user-attachments/assets/ed529c28-cdcb-4f70-938d-45d4ce1cdb30)

1. Try to add a transformation.

1. Observe the following error:

    ![image](https://github.com/user-attachments/assets/f8432e68-2c7f-4682-a26f-edef9b28dd5e)

    ```
    [-31002] AssertionError:
    Traceback (most recent call last):
      File "/code/mathesar/rpc/exceptions/handlers.py", line 16, in safe_func
        return f(*args, **kwargs)
      File "/code/mathesar/rpc/explorations.py", line 189, in run
        exploration_result = run_exploration(exploration_def, conn, limit, offset)
      File "/code/mathesar/utils/explorations.py", line 89, in run_exploration
        records = db_query.get_records(
      File "/code/db/queries/base.py", line 117, in get_records
        table=self.transformed_relation,
      File "/code/db/queries/base.py", line 187, in transformed_relation
        transformed = apply_transformations(
      File "/code/db/transforms/operations/apply.py", line 8, in apply_transformations
        relation = _apply_transform(relation, transform)
      File "/code/db/transforms/operations/apply.py", line 13, in _apply_transform
        assert isinstance(transform, Transform)
    AssertionError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/modernrpc/handlers/jsonhandler.py", line 182, in process_single_request
        result_data = _method.execute(context, args, kwargs)
      File "/usr/local/lib/python3.9/site-packages/modernrpc/core.py", line 143, in execute
        return self.function(*args, **kwargs)
      File "/code/mathesar/rpc/exceptions/handlers.py", line 18, in safe_func
        _raise_generic_error(e)
      File "/code/mathesar/rpc/exceptions/handlers.py", line 25, in _raise_generic_error
        raise RPCException(err_code, e.__class__.__name__ + ": " + str(e))
    modernrpc.exceptions.RPCException: [-31002] AssertionError:
    ```

**Comment by seancolsen** [comment]
Fixed in #3873
