### ISSUE TITLE
Error When Adding Pre-Existing Database

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3907]
## Description
I've encountered the following errors when trying to add a pre-existing database to Mathesar. 
Here is the relevant sections of the log:
```
mathesar_service                | Installing Mathesar on preexisting PostgreSQL database postgres at host aws-0-eu-west-3.pooler.supabase.com...
mathesar_service                | [2024-10-01 13:01:36 +0000] [17] [CRITICAL] WORKER TIMEOUT (pid:32088)
mathesar_service                | [2024-10-01 13:01:36 +0000] [32088] [ERROR] Error handling request /api/rpc/v0/
mathesar-caddy-reverse-proxy-1  | {"level":"error","ts":1727787696.5455995,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"192.168.65.1","remote_port":"45557","client_ip":"192.168.65.1","proto":"HTTP/1.1","method":"POST","host":"localhost","uri":"/api/rpc/v0/","headers":{"Sec-Ch-Ua-Mobile":["?0"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Origin":["http://localhost"],"Sec-Fetch-Site":["same-origin"],"Referer":["http://localhost/databases/"],"Cookie":[],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"],"Dnt":["1"],"Accept":["*/*"],"Sec-Fetch-Dest":["empty"],"Connection":["keep-alive"],"Content-Length":["267"],"X-Csrftoken":["fIlfcX2Vy2KEa92OHh3X9kQekE7b1BUK"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\""],"Content-Type":["application/json"],"Sec-Fetch-Mode":["cors"],"Accept-Language":["en-US,en;q=0.9,es;q=0.8,nb;q=0.7,fr;q=0.6,gl;q=0.5,de;q=0.4"],"Sec-Ch-Ua-Platform":["\"macOS\""]}},"bytes_read":267,"user_id":"","duration":30.073762306,"size":141,"status":500,"resp_headers":{"Server":["Caddy"],"Content-Type":["text/html"],"Content-Length":["141"]}}
mathesar_service                | Traceback (most recent call last):
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
mathesar_service                |     self.handle_request(listener, req, client, addr)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
mathesar_service                |     respiter = self.wsgi(environ, resp.start_response)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
mathesar_service                |     response = self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
mathesar_service                |     response = self._middleware_chain(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/whitenoise/middleware.py", line 124, in __call__
mathesar_service                |     return self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/code/mathesar/middleware.py", line 14, in __call__
mathesar_service                |     response = self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/code/mathesar/middleware.py", line 34, in __call__
mathesar_service                |     response = self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
mathesar_service                |     response = response or self.get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
mathesar_service                |     response = get_response(request)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
mathesar_service                |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
mathesar_service                |     return self.dispatch(request, *args, **kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
mathesar_service                |     return super().dispatch(request, *args, **kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
mathesar_service                |     return bound_method(*args, **kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
mathesar_service                |     return view_func(*args, **kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
mathesar_service                |     return handler(request, *args, **kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/modernrpc/views.py", line 109, in post
mathesar_service                |     result_data = handler.process_request(request_body, context)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/modernrpc/handlers/jsonhandler.py", line 128, in process_request
mathesar_service                |     return self.dumps_result(self.process_single_request(parsed_request, context))
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/modernrpc/handlers/jsonhandler.py", line 182, in process_single_request
mathesar_service                |     result_data = _method.execute(context, args, kwargs)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/modernrpc/core.py", line 143, in execute
mathesar_service                |     return self.function(*args, **kwargs)
mathesar_service                |   File "/code/mathesar/rpc/exceptions/handlers.py", line 16, in safe_func
mathesar_service                |     return f(*args, **kwargs)
mathesar_service                |   File "/code/mathesar/rpc/databases/setup.py", line 99, in connect_existing
mathesar_service                |     result = permissions.set_up_preexisting_database_for_user(
mathesar_service                |   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
mathesar_service                |     return func(*args, **kwds)
mathesar_service                |   File "/code/mathesar/utils/permissions.py", line 77, in set_up_preexisting_database_for_user
mathesar_service                |     install_mathesar(
mathesar_service                |   File "/code/db/install.py", line 31, in install_mathesar
mathesar_service                |     types_install.install_mathesar_on_database(user_db_engine)
mathesar_service                |   File "/code/db/types/install.py", line 22, in install_mathesar_on_database
mathesar_service                |     install_all_casts(engine)
mathesar_service                |   File "/code/db/types/operations/cast.py", line 55, in install_all_casts
mathesar_service                |     create_textual_casts(engine)
mathesar_service                |   File "/code/db/types/operations/cast.py", line 135, in create_textual_casts
mathesar_service                |     create_cast_functions(db_type, type_body_map, engine)
mathesar_service                |   File "/code/db/types/operations/cast.py", line 223, in create_cast_functions
mathesar_service                |     conn.execute(text(query))
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 280, in execute
mathesar_service                |     return self._execute_20(
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
mathesar_service                |     return meth(self, args_10style, kwargs_10style, execution_options)
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
mathesar_service                |     return connection._execute_clauseelement(
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
mathesar_service                |     ret = self._execute_context(
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
mathesar_service                |     self._handle_dbapi_exception(
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
mathesar_service                |     util.raise_(exc_info[1], with_traceback=exc_info[2])
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
mathesar_service                |     raise exception
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
mathesar_service                |     self.dialect.do_execute(
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
mathesar_service                |     cursor.execute(statement, parameters)
mathesar_service                |   File "/usr/local/lib/python3.9/encodings/utf_8.py", line 15, in decode
mathesar_service                |     def decode(input, errors='strict'):
mathesar_service                |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
mathesar_service                |     sys.exit(1)
mathesar_service                | SystemExit: 1
mathesar_service                | [2024-10-01 13:01:36 +0000] [32088] [INFO] Worker exiting (pid: 32088)
mathesar_service                | [2024-10-01 13:01:36 +0000] [32231] [INFO] Booting worker with pid: 32231
```

## Expected behavior
The database installation should complete without errors, but it's currently failing during this process.

## Additional context
This issue occurred while attempting to install Mathesar on a blank PostgreSQL database created in Supabase.

**Comment by Anish9901** [comment]
Looks like the gunicorn webserver is timining out before mathesar finishes up installing on the database.

I did some troubleshooting and here are some statistics.
### On Indian server:
```
mathesar_service_dev  | Installing Mathesar on preexisting PostgreSQL database postgres at host aws-0-ap-south-1.pooler.supabase.com...
mathesar_service_dev  | Types install(time in (s)):  49.267500162124634
mathesar_service_dev  | SQL install(time in (s)):  1.4141161441802979
```
### On US East server:
```
mathesar_service_dev  | Installing Mathesar on preexisting PostgreSQL database postgres at host aws-0-us-east-1.pooler.supabase.com...
mathesar_service_dev  | Types install(time in (s)):  318.6559524536133
mathesar_service_dev  | SQL install(time in (s)):  8.823145866394043
```

The Types install is slowing us down and there is a major speedup that can be achieved here.
